<template>
  <div class="agreement-page">
    <section class="agreement-section">
      <h1>HitLive Privacy Policy</h1>

      <p>
        Privacy policy for a creative community with live sessions, project clips, creator profiles, reporting,
        blocking, and moderation tools.
      </p>
      <p>
        This document is a general template for app use and should be reviewed for the laws and markets that apply to
        the service.
      </p>

      <h2>1. About This Privacy Policy</h2>
      <p>
        This Privacy Policy explains how HitLive collects, uses, stores, shares, and protects information when you use
        our mobile application, live creative sessions, project clips, community threads, creator profiles, and related
        services.
      </p>
      <p>
        HitLive is built around creative process, professional exchange, and independent work. Because the service
        includes live streaming, project clips, comments, following, reporting, blocking, and moderation tools, some
        information may be visible to other users depending on how you use the app.
      </p>

      <h2>2. Information We Collect</h2>
      <p>
        We may collect information you provide directly, information generated by your use of HitLive, and information
        from third-party services you choose to connect.
      </p>

      <h2>3. Account Information</h2>
      <p>
        When you create or use an account, we may collect your username, display name, profile photo, login credentials
        or authentication identifiers, profile details, account preferences, creator category, and information connected
        to third-party login services if you choose to use them.
      </p>

      <h2>4. User Content and Community Activity</h2>
      <p>
        We may collect content you create, upload, stream, record, publish, or share, including live video, project
        clips, images, captions, portfolio notes, discussion posts, comments, replies, feedback, likes, follows, saves,
        reports, and other interactions.
      </p>
      <p>
        If you participate in a live session, we may process video, audio, chat messages, viewer activity, stream
        metadata, moderation signals, and technical information needed to operate the stream.
      </p>

      <h2>5. Professional and Project Information</h2>
      <p>
        You may choose to provide information about your creative field, tools, workflow, portfolio, projects,
        techniques, availability, or professional interests.
      </p>
      <p>
        You should avoid sharing confidential client work, private business information, trade secrets, unreleased
        materials, or third-party assets unless you have permission.
      </p>

      <h2>6. Device and Usage Information</h2>
      <p>
        We may automatically collect technical and usage information, such as device type, operating system, app version,
        language and region settings, IP address, crash logs, diagnostic data, performance data, pages viewed, streams
        watched, clips played, search activity, recommendation interactions, and feature usage.
      </p>

      <h2>7. Camera, Microphone, Photos, and Notifications</h2>
      <p>
        HitLive may request access to your camera, microphone, photo library, media files, or notifications depending on
        the features you use.
      </p>
      <p>
        Camera and microphone access may be used for live sessions, recorded clips, profile media, and creator tools.
      </p>
      <p>
        Photo or media access may be used to upload project clips, images, portfolio materials, or other content.
      </p>
      <p>
        Notifications may be used for account activity, followed creator updates, live session alerts, community
        interactions, and service messages.
      </p>
      <p>You can manage device permissions through your device settings.</p>

      <h2>8. How We Use Information</h2>
      <p>We use information to provide, operate, maintain, personalize, and improve HitLive.</p>
      <p>
        This includes creating and managing accounts, enabling live sessions and clips, showing creator profiles,
        supporting community threads, displaying comments and follows, recommending content, providing moderation and
        safety tools, processing reports, preventing abuse, improving performance, fixing bugs, providing support through
        in-app features, developing new features, and complying with legal obligations.
      </p>

      <h2>9. Public and Shared Information</h2>
      <p>
        HitLive is a community platform. Information you choose to make public may be visible to other users, including
        your profile, creator category, live sessions, project clips, comments, discussion posts, follows, and other
        visible interactions.
      </p>
      <p>
        Please be careful when sharing personal, professional, or project-related information. Do not post private
        information about others without permission.
      </p>

      <h2>10. How We Share Information</h2>
      <p>We do not sell your personal information.</p>
      <p>
        We may share information with other users according to app features and your settings. We may share information
        with service providers that help us operate HitLive, such as cloud hosting, streaming infrastructure, storage,
        analytics, crash reporting, authentication, customer support, content moderation, security, and payment providers.
      </p>
      <p>
        We may disclose information for safety, legal, and compliance reasons, including to comply with law, enforce our
        terms, investigate abuse or fraud, protect users, protect the service, or respond to emergencies.
      </p>
      <p>
        If HitLive is involved in a merger, acquisition, financing, restructuring, or sale of assets, information may be
        transferred as part of that transaction, subject to appropriate safeguards.
      </p>

      <h2>11. Third-Party Services</h2>
      <p>
        HitLive may include third-party services such as app stores, payment providers, analytics tools, streaming
        infrastructure, login providers, hosting services, or external links.
      </p>
      <p>
        Third-party services may collect or process information according to their own privacy policies. We are not
        responsible for the privacy practices of third-party services.
      </p>

      <h2>12. Moderation, Reports, and Safety</h2>
      <p>
        When users report content or accounts, we may collect report details, reported content, account identifiers,
        related messages or interactions, and moderation history.
      </p>
      <p>
        We may use this information to investigate violations, enforce community rules, prevent harm, reduce abuse,
        improve safety systems, and comply with legal obligations.
      </p>

      <h2>13. Data Retention</h2>
      <p>
        We retain information for as long as needed to provide HitLive, maintain accounts, operate features, comply with
        legal obligations, resolve disputes, enforce terms, prevent abuse, and protect the service.
      </p>
      <p>
        User content may remain available until you delete it or your account is deleted, unless retention is required
        for safety, legal, backup, dispute, moderation, or operational reasons.
      </p>
      <p>
        Some deleted information may remain in backups, logs, or cached systems for a limited period before being
        removed.
      </p>

      <h2>14. Your Choices and Rights</h2>
      <p>
        Depending on your location and applicable law, you may have rights to access, correct, delete, restrict, object
        to processing of, or request a copy of your personal information.
      </p>
      <p>
        You may also manage account details, content visibility, notification settings, blocked users, and device
        permissions through the app or device settings where available.
      </p>

      <h2>15. Account Deletion</h2>
      <p>If account deletion features are available, you may request deletion through the app.</p>
      <p>
        When your account is deleted, we will delete or anonymize personal information associated with your account
        unless we need to retain certain information for legal, security, fraud prevention, dispute resolution,
        moderation, backup, or operational reasons.
      </p>
      <p>
        Content shared with others, reports, moderation records, or cached copies may not disappear immediately from all
        systems.
      </p>

      <h2>16. Children and Minors</h2>
      <p>
        HitLive is not intended for children under 13 years old, or under the minimum age required by applicable law.
      </p>
      <p>
        We do not knowingly collect personal information from children who are not allowed to use HitLive. If we learn
        that such information has been collected, we will take reasonable steps to delete it.
      </p>

      <h2>17. International Data Processing</h2>
      <p>
        HitLive may process and store information in countries or regions other than where you live. Data protection laws
        may differ from those in your location.
      </p>
      <p>Where required, we use appropriate safeguards for international data transfers.</p>

      <h2>18. Security</h2>
      <p>We use reasonable technical, administrative, and organizational measures to help protect information.</p>
      <p>
        However, no method of transmission or storage is completely secure. We cannot guarantee absolute security of
        information.
      </p>

      <h2>19. User Responsibility</h2>
      <p>You are responsible for the information and content you choose to share on HitLive.</p>
      <p>
        Do not share passwords, payment information, identity documents, private addresses, confidential client
        materials, private business records, unreleased work, or private information about other people unless you have
        permission and understand the risks.
      </p>

      <h2>20. Changes to This Privacy Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. If changes are significant, we may provide notice through
        the app or by other reasonable means.
      </p>
      <p>Your continued use of HitLive after updates means you accept the revised Privacy Policy.</p>
    </section>
  </div>
</template>

<script>
export default {
  name: 'HitLivePrivacyPolicy'
}
</script>

<style scoped>
.agreement-page {
  box-sizing: border-box;
  width: 100%;
  min-height: 100vh;
  padding: 24px 18px;
  background: #ffffff;
  color: #222222;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
  line-height: 1.7;
}

.agreement-section {
  max-width: 860px;
  margin: 0 auto;
}

h1 {
  margin: 0 0 16px;
  font-size: 28px;
  font-weight: 700;
  line-height: 1.3;
  color: #111111;
}

h2 {
  margin: 28px 0 10px;
  font-size: 18px;
  font-weight: 700;
  line-height: 1.4;
  color: #111111;
}

p {
  margin: 0 0 14px;
  font-size: 15px;
  color: #333333;
}

@media screen and (max-width: 600px) {
  .agreement-page {
    padding: 20px 16px;
  }

  h1 {
    font-size: 24px;
  }

  h2 {
    font-size: 17px;
  }

  p {
    font-size: 14px;
  }
}
</style>
